# Generated by Django 4.2.3 on 2023-07-04 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenses',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 9, 46, 55, 428560)),
        ),
        migrations.AlterField(
            model_name='licenses',
            name='version',
            field=models.CharField(max_length=6),
        ),
    ]
