# Generated by Django 4.2.3 on 2023-07-04 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_licenses_expiration_date_alter_licenses_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenses',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 9, 47, 23, 390417)),
        ),
    ]
