# Generated by Django 4.2.3 on 2023-07-04 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_alter_licenses_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenses',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 10, 22, 10, 341535)),
        ),
    ]
